##################################################################################################
# 1、该文件中维护基本不会改变的配置
# 2、每个环境有对应的配置，请规范使用每个环境配置;比如开发环境需要访问swagger接口文档，但在正式环境需要屏蔽,每个环境的资源分配不一样
# 3、如果使用nacos配置中心，建议将本地环境 “dev|test|prod” 配置屏蔽，防止使用过程中混淆;使用本地配置，屏蔽下面nacos配置即可
#    nacos启动命令（单机模式）：
#      linux:   sh startup.sh -m standalone 或 bash startup.sh -m standalone
#      windows: startup.cmd -m standalone
#    nacos关闭命令：sh shutdown.sh   或   shutdown.cmd
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
##################################################################################################
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: oh-boot
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 设置 java.util.Date, Calendar 序列化、反序列化的格式
    locale: zh                        # 当地时区
    time-zone: GMT+8                  # 设置全局时区
    # 设置对象或被@JsonInclude注解的属性的序列化方式。NON_NULL 表示不为空的属性才会序列化,具体属性可看JsonInclude.Include
    # default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false   # 禁止将 java.util.Date, Calendar 序列化为数字(时间戳)
      FAIL_ON_EMPTY_BEANS: false         # 序列化时，对象为 null，是否抛异常
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false  # 反序列化时，json 中包含 pojo 不存在属性时，是否抛异常

#easy trans 数据翻译组件
easy-trans:
  is-enable-redis: false      # 启用redis缓存 如果不用redis请设置为false
  dict-use-redis: true        # 字典缓存放到redis
  is-enable-global: true      # 启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-tile: true        # 启用平铺模式
  multiple-data-sources: true # 启用多数据源
  # db-type: mysql            # 反向翻译数据库类型 mysql

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.iris.*.entity # 实体扫描，多个package用逗号或者分号分隔
  global-config:
    # 数据库相关配置
    db-config:
      id-type: AUTO  # ID自增
      # logic-delete-field: db_status # 全局逻辑删除的实体字段名(since 3.3.0)
      logic-delete-value: 0      # 逻辑已删除值
      logic-not-delete-value: 1  # 逻辑未删除值
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

# nacos相关配置
#nacos:
#  config:
#    # nacos会根据配置怎么找到对应的配置文件规则：prefix−{spring.profile.active}.${file-extension}
#    # spring.profiles.active 为空时，对应的连接符 - 也将不存在，，dataId 的拼接格式变成 ${prefix}.${file-extension}
#    bootstrap:
#      enable: true                                   #开启系统启动时预读取nacos的配置，用于满足@Value注入数据的场景
#    namespace: 3b00ce0d-eca1-4ef0-a764-199212d930ac  # 配置所属命名空间的id,此处我们配置名称为dev的id，可以在命名空间列表查看id的值
#    prefix: iris                                     # 配置文件的前缀,默认为 spring.application.name 的值
#    group: ${spring.profiles.active}                 # 配置所属分组
#    data-id: iris-dev.yaml                           # 配置ID
#    type: yaml                                       # 配置文件类型,对应nacos配置页面的配置格式，默认是properties
#    server-addr: localhost:8848                      # nacos服务器地址
#    auto-refresh: true                               # 开启自动刷新nacos配置
#    remote-first: true                               # 针对配置项同名的情况，是否允许nacos的配置覆盖本地的配置
#    # 如果开启了鉴权，需配置用户名和密码
#    username: nacos
#    password: nacos