/*
 Navicat Premium Dump SQL

 Source Server         : pg
 Source Server Type    : PostgreSQL
 Source Server Version : 180003 (180003)
 Source Host           : localhost:5432
 Source Catalog        : stepping-stone
 Source Schema         : oh_boot

 Target Server Type    : PostgreSQL
 Target Server Version : 180003 (180003)
 File Encoding         : 65001

 Date: 27/03/2026 19:51:02
*/


-- ----------------------------
-- Sequence structure for bpmn_flow_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."bpmn_flow_id_seq";
CREATE SEQUENCE "oh_boot"."bpmn_flow_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."bpmn_flow_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for bpmn_flow_node_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."bpmn_flow_node_id_seq";
CREATE SEQUENCE "oh_boot"."bpmn_flow_node_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."bpmn_flow_node_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for bpmn_task_record_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."bpmn_task_record_id_seq";
CREATE SEQUENCE "oh_boot"."bpmn_task_record_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."bpmn_task_record_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for data_app_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."data_app_id_seq";
CREATE SEQUENCE "oh_boot"."data_app_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."data_app_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for data_function_authority_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."data_function_authority_id_seq";
CREATE SEQUENCE "oh_boot"."data_function_authority_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."data_function_authority_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for data_function_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."data_function_id_seq";
CREATE SEQUENCE "oh_boot"."data_function_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."data_function_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for data_message_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."data_message_id_seq";
CREATE SEQUENCE "oh_boot"."data_message_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."data_message_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for oh_project_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."oh_project_id_seq";
CREATE SEQUENCE "oh_boot"."oh_project_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."oh_project_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for oh_task_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."oh_task_id_seq";
CREATE SEQUENCE "oh_boot"."oh_task_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."oh_task_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for oh_work_order_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "oh_boot"."oh_work_order_id_seq";
CREATE SEQUENCE "oh_boot"."oh_work_order_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "oh_boot"."oh_work_order_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Table structure for bpmn_flow
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."bpmn_flow";
CREATE TABLE "oh_boot"."bpmn_flow" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "key_code" varchar(30) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "xml" text COLLATE "pg_catalog"."default" NOT NULL,
  "svg_str" text COLLATE "pg_catalog"."default",
  "version_tag" varchar(50) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "note" varchar(500) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "db_status" int2 DEFAULT 1,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6)
)
;
ALTER TABLE "oh_boot"."bpmn_flow" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."key_code" IS '流程code';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."name" IS '流程名称';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."xml" IS 'bpmn的xml字符串';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."svg_str" IS 'svg图片字符串';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."version_tag" IS '标签';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."note" IS '说明';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."bpmn_flow"."update_time" IS '更新时间';
COMMENT ON TABLE "oh_boot"."bpmn_flow" IS '自定义流程表';

-- ----------------------------
-- Records of bpmn_flow
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for bpmn_flow_node
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."bpmn_flow_node";
CREATE TABLE "oh_boot"."bpmn_flow_node" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "proc_def_id" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "act_def_id" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "node_name" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "element_type" varchar(50) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "note" varchar(300) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "db_status" int2 DEFAULT 1,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6)
)
;
ALTER TABLE "oh_boot"."bpmn_flow_node" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."proc_def_id" IS '流程定义ID';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."act_def_id" IS '环节ID';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."node_name" IS '环节名称';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."element_type" IS '环节类型,UserTask、ExclusiveGateway等';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."note" IS '备注';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."bpmn_flow_node"."update_time" IS '更新时间';
COMMENT ON TABLE "oh_boot"."bpmn_flow_node" IS '环节定义表';

-- ----------------------------
-- Records of bpmn_flow_node
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for bpmn_task_record
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."bpmn_task_record";
CREATE TABLE "oh_boot"."bpmn_task_record" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "proc_def_id" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "proc_inst_id" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "act_inst_id" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "task_id" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "task_def_id" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "task_name" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "from_act_inst_id" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "from_task_id" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "from_task_def_id" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "from_task_name" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "run_mark" int4 DEFAULT 0,
  "assignee" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "assignee_name" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "start_time" timestamp(6),
  "end_time" timestamp(6),
  "duration" int8,
  "db_status" int2 DEFAULT 1,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6)
)
;
ALTER TABLE "oh_boot"."bpmn_task_record" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."proc_def_id" IS '流程定义ID';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."proc_inst_id" IS '环节实例ID';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."act_inst_id" IS '环节实例ID';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."task_id" IS '任务ID';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."task_def_id" IS '环节key';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."task_name" IS '环节名称';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."from_act_inst_id" IS '来自于环节实例ID';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."from_task_id" IS '来自于任务key';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."from_task_def_id" IS '来自于环节ID';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."from_task_name" IS '来自于环节名称';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."run_mark" IS '当前标识，默认0，1标识当前环节';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."assignee" IS '受理人ID';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."assignee_name" IS '受理人';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."start_time" IS '开始时间';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."end_time" IS '结束时间';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."duration" IS '时长';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."bpmn_task_record"."update_time" IS '更新时间';
COMMENT ON TABLE "oh_boot"."bpmn_task_record" IS '环节运行记录表';

-- ----------------------------
-- Records of bpmn_task_record
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for data_app
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."data_app";
CREATE TABLE "oh_boot"."data_app" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "client_id" varchar(45) COLLATE "pg_catalog"."default" NOT NULL,
  "secret_key" varchar(45) COLLATE "pg_catalog"."default" NOT NULL,
  "remark" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6),
  "db_status" int2 DEFAULT 1
)
;
ALTER TABLE "oh_boot"."data_app" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."data_app"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."data_app"."name" IS '客户端名称';
COMMENT ON COLUMN "oh_boot"."data_app"."client_id" IS '客户端ID';
COMMENT ON COLUMN "oh_boot"."data_app"."secret_key" IS '密钥';
COMMENT ON COLUMN "oh_boot"."data_app"."remark" IS '备注';
COMMENT ON COLUMN "oh_boot"."data_app"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."data_app"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."data_app"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."data_app"."update_time" IS '更新时间';
COMMENT ON COLUMN "oh_boot"."data_app"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON TABLE "oh_boot"."data_app" IS '客户端';

-- ----------------------------
-- Records of data_app
-- ----------------------------
BEGIN;
INSERT INTO "oh_boot"."data_app" ("id", "name", "client_id", "secret_key", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (1, '饿了吧集团', 'C0001', 'c28a8120682d4b4fa50325ed34748e0e', '饿了吧接口对接配置', 10000, '2023-07-29 13:04:34', 10000, '2023-07-29 13:04:34', 1);
INSERT INTO "oh_boot"."data_app" ("id", "name", "client_id", "secret_key", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (2, '阿狸芭比公司', 'C0002', '0682d4b4fa50325ed347', '', 10000, '2023-07-29 13:05:28', 10000, '2023-07-29 13:05:28', 1);
INSERT INTO "oh_boot"."data_app" ("id", "name", "client_id", "secret_key", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (3, '支付包', 'C003', '8a8120682d4b4fa50325ed', '', 10000, '2023-08-12 19:53:17', 10000, '2023-08-12 19:53:17', 1);
COMMIT;

-- ----------------------------
-- Table structure for data_function
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."data_function";
CREATE TABLE "oh_boot"."data_function" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "func_code" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "is_async" int2 NOT NULL DEFAULT 0,
  "remark" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6),
  "db_status" int2 DEFAULT 1
)
;
ALTER TABLE "oh_boot"."data_function" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."data_function"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."data_function"."name" IS '功能名称';
COMMENT ON COLUMN "oh_boot"."data_function"."func_code" IS '功能号';
COMMENT ON COLUMN "oh_boot"."data_function"."is_async" IS '是否异步0否1是';
COMMENT ON COLUMN "oh_boot"."data_function"."remark" IS '备注';
COMMENT ON COLUMN "oh_boot"."data_function"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."data_function"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."data_function"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."data_function"."update_time" IS '更新时间';
COMMENT ON COLUMN "oh_boot"."data_function"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON TABLE "oh_boot"."data_function" IS '功能列表';

-- ----------------------------
-- Records of data_function
-- ----------------------------
BEGIN;
INSERT INTO "oh_boot"."data_function" ("id", "name", "func_code", "is_async", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (1, '用户信息上传', 'F1001', 1, '用户信息同步', 10000, '2023-08-02 21:29:22', 10000, '2023-07-30 13:32:13', 1);
INSERT INTO "oh_boot"."data_function" ("id", "name", "func_code", "is_async", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (2, '账单查询', 'F1002', 0, '查询账单信息', 10000, '2023-08-02 21:29:22', 10000, '2023-07-30 13:32:18', 1);
INSERT INTO "oh_boot"."data_function" ("id", "name", "func_code", "is_async", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (3, '新增工单', 'F1003', 1, '', 10000, '2024-02-28 21:50:47', NULL, NULL, 1);
COMMIT;

-- ----------------------------
-- Table structure for data_function_authority
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."data_function_authority";
CREATE TABLE "oh_boot"."data_function_authority" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "client_id" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "func_code" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "remark" varchar(100) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6),
  "db_status" int2 DEFAULT 1
)
;
ALTER TABLE "oh_boot"."data_function_authority" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."data_function_authority"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."data_function_authority"."client_id" IS '客户端ID';
COMMENT ON COLUMN "oh_boot"."data_function_authority"."func_code" IS '功能号';
COMMENT ON COLUMN "oh_boot"."data_function_authority"."remark" IS '备注';
COMMENT ON COLUMN "oh_boot"."data_function_authority"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."data_function_authority"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."data_function_authority"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."data_function_authority"."update_time" IS '更新时间';
COMMENT ON COLUMN "oh_boot"."data_function_authority"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON TABLE "oh_boot"."data_function_authority" IS '客户端接口授权';

-- ----------------------------
-- Records of data_function_authority
-- ----------------------------
BEGIN;
INSERT INTO "oh_boot"."data_function_authority" ("id", "client_id", "func_code", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (1, 'C0001', 'F1001', NULL, 10000, '2023-08-13 14:36:19', 10000, '2023-08-13 14:36:19', 1);
INSERT INTO "oh_boot"."data_function_authority" ("id", "client_id", "func_code", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (2, 'C0001', 'F1002', NULL, 10000, '2023-08-13 14:36:19', 10000, '2023-08-13 14:36:19', 1);
INSERT INTO "oh_boot"."data_function_authority" ("id", "client_id", "func_code", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (3, 'C0002', 'F1001', NULL, 10000, '2023-08-13 14:36:29', 10000, '2023-08-13 14:36:29', 1);
INSERT INTO "oh_boot"."data_function_authority" ("id", "client_id", "func_code", "remark", "creator", "create_time", "updater", "update_time", "db_status") VALUES (4, 'C0001', 'F1003', NULL, 10000, '2024-02-28 21:51:00', NULL, NULL, 1);
COMMIT;

-- ----------------------------
-- Table structure for data_message
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."data_message";
CREATE TABLE "oh_boot"."data_message" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "client_id" varchar(50) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "func_code" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "topic" varchar(50) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "json_str" varchar(3000) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "state" varchar(1) COLLATE "pg_catalog"."default" DEFAULT '0'::character varying,
  "result_msg" varchar(3000) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "note" varchar(500) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "creator" int8,
  "create_time" timestamp(3) DEFAULT NULL::timestamp without time zone,
  "updater" int8,
  "update_time" timestamp(6),
  "db_status" int2 DEFAULT 1
)
;
ALTER TABLE "oh_boot"."data_message" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."data_message"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."data_message"."client_id" IS '客户端ID';
COMMENT ON COLUMN "oh_boot"."data_message"."func_code" IS '功能号';
COMMENT ON COLUMN "oh_boot"."data_message"."topic" IS '主题';
COMMENT ON COLUMN "oh_boot"."data_message"."json_str" IS '请求参数';
COMMENT ON COLUMN "oh_boot"."data_message"."state" IS '状态0未处理1处理2未找到对应的服务类3业务处理失败';
COMMENT ON COLUMN "oh_boot"."data_message"."result_msg" IS '响应消息';
COMMENT ON COLUMN "oh_boot"."data_message"."note" IS '备注';
COMMENT ON COLUMN "oh_boot"."data_message"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."data_message"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."data_message"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."data_message"."update_time" IS '更新时间';
COMMENT ON COLUMN "oh_boot"."data_message"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON TABLE "oh_boot"."data_message" IS '接口参数数据';

-- ----------------------------
-- Records of data_message
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for oh_project
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."oh_project";
CREATE TABLE "oh_boot"."oh_project" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "project_code" varchar(50) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "project_name" varchar(80) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "project_alias" varchar(50) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "start_time" date,
  "end_time" date,
  "director" int8,
  "director_name" varchar(60) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "status" int2,
  "db_status" int2 DEFAULT 1,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6)
)
;
ALTER TABLE "oh_boot"."oh_project" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."oh_project"."id" IS 'ID';
COMMENT ON COLUMN "oh_boot"."oh_project"."project_code" IS '项目编码';
COMMENT ON COLUMN "oh_boot"."oh_project"."project_name" IS '项目名称';
COMMENT ON COLUMN "oh_boot"."oh_project"."project_alias" IS '别名';
COMMENT ON COLUMN "oh_boot"."oh_project"."start_time" IS '开始时间';
COMMENT ON COLUMN "oh_boot"."oh_project"."end_time" IS '结束时间';
COMMENT ON COLUMN "oh_boot"."oh_project"."director" IS '负责人ID';
COMMENT ON COLUMN "oh_boot"."oh_project"."director_name" IS '负责人姓名';
COMMENT ON COLUMN "oh_boot"."oh_project"."status" IS '状态（1开始2暂停3关闭）';
COMMENT ON COLUMN "oh_boot"."oh_project"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON COLUMN "oh_boot"."oh_project"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."oh_project"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."oh_project"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."oh_project"."update_time" IS '更新时间';
COMMENT ON TABLE "oh_boot"."oh_project" IS '项目信息表';

-- ----------------------------
-- Records of oh_project
-- ----------------------------
BEGIN;
INSERT INTO "oh_boot"."oh_project" ("id", "project_code", "project_name", "project_alias", "start_time", "end_time", "director", "director_name", "status", "db_status", "creator", "create_time", "updater", "update_time") VALUES (2, 'P1001', '垫脚石计划', '垫脚石', '2022-12-01', NULL, 10001, '王小费', 1, 1, NULL, '2022-12-04 14:09:33', NULL, '2022-12-04 14:09:37');
COMMIT;

-- ----------------------------
-- Table structure for oh_project_log
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."oh_project_log";
CREATE TABLE "oh_boot"."oh_project_log" (
  "id" int8 NOT NULL,
  "project_id" int4,
  "task_id" int8,
  "operation" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "remark" varchar(500) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "db_status" int2 DEFAULT 1,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6)
)
;
ALTER TABLE "oh_boot"."oh_project_log" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."oh_project_log"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."oh_project_log"."project_id" IS '项目ID';
COMMENT ON COLUMN "oh_boot"."oh_project_log"."task_id" IS '任务ID';
COMMENT ON COLUMN "oh_boot"."oh_project_log"."operation" IS '操作类型';
COMMENT ON COLUMN "oh_boot"."oh_project_log"."remark" IS '备注';
COMMENT ON COLUMN "oh_boot"."oh_project_log"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON COLUMN "oh_boot"."oh_project_log"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."oh_project_log"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."oh_project_log"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."oh_project_log"."update_time" IS '更新时间';
COMMENT ON TABLE "oh_boot"."oh_project_log" IS '项目、任务操作日志';

-- ----------------------------
-- Records of oh_project_log
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for oh_task
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."oh_task";
CREATE TABLE "oh_boot"."oh_task" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "project_id" int4 NOT NULL,
  "task_title" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "note" varchar(500) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "task_type" char(1) COLLATE "pg_catalog"."default" NOT NULL,
  "parent_id" int8 NOT NULL DEFAULT 0,
  "has_child" int2,
  "start_time" timestamp(6),
  "end_time" timestamp(6),
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '1'::bpchar,
  "remark" varchar(500) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "db_status" int2 DEFAULT 1,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6)
)
;
ALTER TABLE "oh_boot"."oh_task" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."oh_task"."id" IS '序号';
COMMENT ON COLUMN "oh_boot"."oh_task"."project_id" IS '所属项目';
COMMENT ON COLUMN "oh_boot"."oh_task"."task_title" IS '任务标题';
COMMENT ON COLUMN "oh_boot"."oh_task"."note" IS '任务描述';
COMMENT ON COLUMN "oh_boot"."oh_task"."task_type" IS '1任务2需求3设计4缺陷9其他';
COMMENT ON COLUMN "oh_boot"."oh_task"."parent_id" IS '父级任务ID';
COMMENT ON COLUMN "oh_boot"."oh_task"."has_child" IS '是否有子任务';
COMMENT ON COLUMN "oh_boot"."oh_task"."start_time" IS '计划开始时间';
COMMENT ON COLUMN "oh_boot"."oh_task"."end_time" IS '计划结束时间';
COMMENT ON COLUMN "oh_boot"."oh_task"."status" IS '状态（1待办项2进行中3已完成）';
COMMENT ON COLUMN "oh_boot"."oh_task"."remark" IS '备注';
COMMENT ON COLUMN "oh_boot"."oh_task"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON COLUMN "oh_boot"."oh_task"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."oh_task"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."oh_task"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."oh_task"."update_time" IS '更新时间';
COMMENT ON TABLE "oh_boot"."oh_task" IS '任务表';

-- ----------------------------
-- Records of oh_task
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for oh_task_user
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."oh_task_user";
CREATE TABLE "oh_boot"."oh_task_user" (
  "id" int8 NOT NULL,
  "task_id" int8 NOT NULL,
  "user_id" int8 NOT NULL,
  "nick_name" varchar(30) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "person_type" char(1) COLLATE "pg_catalog"."default" NOT NULL,
  "db_status" int2 DEFAULT 1,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6)
)
;
ALTER TABLE "oh_boot"."oh_task_user" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."oh_task_user"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."oh_task_user"."task_id" IS '任务ID';
COMMENT ON COLUMN "oh_boot"."oh_task_user"."user_id" IS '人员ID';
COMMENT ON COLUMN "oh_boot"."oh_task_user"."nick_name" IS '用户昵称';
COMMENT ON COLUMN "oh_boot"."oh_task_user"."person_type" IS '人员类型1负责人2协作人';
COMMENT ON COLUMN "oh_boot"."oh_task_user"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON COLUMN "oh_boot"."oh_task_user"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."oh_task_user"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."oh_task_user"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."oh_task_user"."update_time" IS '更新时间';
COMMENT ON TABLE "oh_boot"."oh_task_user" IS '任务人员表';

-- ----------------------------
-- Records of oh_task_user
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for oh_work_order
-- ----------------------------
DROP TABLE IF EXISTS "oh_boot"."oh_work_order";
CREATE TABLE "oh_boot"."oh_work_order" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "order_code" varchar(40) COLLATE "pg_catalog"."default" NOT NULL,
  "order_source" varchar(2) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "report_time" timestamp(6),
  "incident_time" timestamp(6),
  "end_time" timestamp(6),
  "title" varchar(50) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "comment" varchar(2000) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "address" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "geo_x" numeric(12,9) DEFAULT NULL::numeric,
  "geo_y" numeric(12,9) DEFAULT NULL::numeric,
  "category" int4,
  "extend_json" varchar(300) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "note" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "db_status" int2 DEFAULT 1,
  "creator" int8,
  "create_time" timestamp(6),
  "updater" int8,
  "update_time" timestamp(6)
)
;
ALTER TABLE "oh_boot"."oh_work_order" OWNER TO "postgres";
COMMENT ON COLUMN "oh_boot"."oh_work_order"."id" IS 'id';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."order_code" IS '工单编码';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."order_source" IS '工单来源';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."report_time" IS '上报时间';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."incident_time" IS '事发时间';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."end_time" IS '结束时间';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."title" IS '标题';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."comment" IS '内容';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."address" IS '位置';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."geo_x" IS '经度';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."geo_y" IS '纬度';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."category" IS '类别';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."extend_json" IS 'json扩展字段';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."note" IS '备注';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."db_status" IS '数据状态标识 0：已删除，1：正常';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."creator" IS '创建者';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."create_time" IS '创建时间';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."updater" IS '更新者';
COMMENT ON COLUMN "oh_boot"."oh_work_order"."update_time" IS '更新时间';
COMMENT ON TABLE "oh_boot"."oh_work_order" IS '工单表';

-- ----------------------------
-- Records of oh_work_order
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."bpmn_flow_id_seq"
OWNED BY "oh_boot"."bpmn_flow"."id";
SELECT setval('"oh_boot"."bpmn_flow_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."bpmn_flow_node_id_seq"
OWNED BY "oh_boot"."bpmn_flow_node"."id";
SELECT setval('"oh_boot"."bpmn_flow_node_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."bpmn_task_record_id_seq"
OWNED BY "oh_boot"."bpmn_task_record"."id";
SELECT setval('"oh_boot"."bpmn_task_record_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."data_app_id_seq"
OWNED BY "oh_boot"."data_app"."id";
SELECT setval('"oh_boot"."data_app_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."data_function_authority_id_seq"
OWNED BY "oh_boot"."data_function_authority"."id";
SELECT setval('"oh_boot"."data_function_authority_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."data_function_id_seq"
OWNED BY "oh_boot"."data_function"."id";
SELECT setval('"oh_boot"."data_function_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."data_message_id_seq"
OWNED BY "oh_boot"."data_message"."id";
SELECT setval('"oh_boot"."data_message_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."oh_project_id_seq"
OWNED BY "oh_boot"."oh_project"."id";
SELECT setval('"oh_boot"."oh_project_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."oh_task_id_seq"
OWNED BY "oh_boot"."oh_task"."id";
SELECT setval('"oh_boot"."oh_task_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "oh_boot"."oh_work_order_id_seq"
OWNED BY "oh_boot"."oh_work_order"."id";
SELECT setval('"oh_boot"."oh_work_order_id_seq"', 1, false);

-- ----------------------------
-- Auto increment value for bpmn_flow
-- ----------------------------
SELECT setval('"oh_boot"."bpmn_flow_id_seq"', 1, false);

-- ----------------------------
-- Uniques structure for table bpmn_flow
-- ----------------------------
ALTER TABLE "oh_boot"."bpmn_flow" ADD CONSTRAINT "bpmn_flow_key_code_key" UNIQUE ("key_code");

-- ----------------------------
-- Primary Key structure for table bpmn_flow
-- ----------------------------
ALTER TABLE "oh_boot"."bpmn_flow" ADD CONSTRAINT "bpmn_flow_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for bpmn_flow_node
-- ----------------------------
SELECT setval('"oh_boot"."bpmn_flow_node_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table bpmn_flow_node
-- ----------------------------
CREATE INDEX "idx_01" ON "oh_boot"."bpmn_flow_node" USING btree (
  "proc_def_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table bpmn_flow_node
-- ----------------------------
ALTER TABLE "oh_boot"."bpmn_flow_node" ADD CONSTRAINT "bpmn_flow_node_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for bpmn_task_record
-- ----------------------------
SELECT setval('"oh_boot"."bpmn_task_record_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table bpmn_task_record
-- ----------------------------
CREATE INDEX "bpmn_task_record_proc_inst_id_idx" ON "oh_boot"."bpmn_task_record" USING btree (
  "proc_inst_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table bpmn_task_record
-- ----------------------------
ALTER TABLE "oh_boot"."bpmn_task_record" ADD CONSTRAINT "bpmn_task_record_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for data_app
-- ----------------------------
SELECT setval('"oh_boot"."data_app_id_seq"', 1, false);

-- ----------------------------
-- Uniques structure for table data_app
-- ----------------------------
ALTER TABLE "oh_boot"."data_app" ADD CONSTRAINT "data_app_client_id_key" UNIQUE ("client_id");

-- ----------------------------
-- Primary Key structure for table data_app
-- ----------------------------
ALTER TABLE "oh_boot"."data_app" ADD CONSTRAINT "data_app_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for data_function
-- ----------------------------
SELECT setval('"oh_boot"."data_function_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table data_function
-- ----------------------------
CREATE INDEX "data_function_index2" ON "oh_boot"."data_function" USING btree (
  "func_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table data_function
-- ----------------------------
ALTER TABLE "oh_boot"."data_function" ADD CONSTRAINT "data_function_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for data_function_authority
-- ----------------------------
SELECT setval('"oh_boot"."data_function_authority_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table data_function_authority
-- ----------------------------
CREATE INDEX "index2" ON "oh_boot"."data_function_authority" USING btree (
  "client_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table data_function_authority
-- ----------------------------
ALTER TABLE "oh_boot"."data_function_authority" ADD CONSTRAINT "data_function_authority_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for data_message
-- ----------------------------
SELECT setval('"oh_boot"."data_message_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table data_message
-- ----------------------------
CREATE INDEX "data_message_idx_01" ON "oh_boot"."data_message" USING btree (
  "topic" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "client_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "func_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table data_message
-- ----------------------------
ALTER TABLE "oh_boot"."data_message" ADD CONSTRAINT "data_message_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for oh_project
-- ----------------------------
SELECT setval('"oh_boot"."oh_project_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table oh_project
-- ----------------------------
ALTER TABLE "oh_boot"."oh_project" ADD CONSTRAINT "oh_project_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table oh_project_log
-- ----------------------------
ALTER TABLE "oh_boot"."oh_project_log" ADD CONSTRAINT "oh_project_log_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for oh_task
-- ----------------------------
SELECT setval('"oh_boot"."oh_task_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table oh_task
-- ----------------------------
ALTER TABLE "oh_boot"."oh_task" ADD CONSTRAINT "oh_task_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table oh_task_user
-- ----------------------------
CREATE INDEX "idx_02" ON "oh_boot"."oh_task_user" USING btree (
  "task_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table oh_task_user
-- ----------------------------
ALTER TABLE "oh_boot"."oh_task_user" ADD CONSTRAINT "oh_task_user_task_id_user_id_key" UNIQUE ("task_id", "user_id");

-- ----------------------------
-- Primary Key structure for table oh_task_user
-- ----------------------------
ALTER TABLE "oh_boot"."oh_task_user" ADD CONSTRAINT "oh_task_user_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for oh_work_order
-- ----------------------------
SELECT setval('"oh_boot"."oh_work_order_id_seq"', 1, false);

-- ----------------------------
-- Uniques structure for table oh_work_order
-- ----------------------------
ALTER TABLE "oh_boot"."oh_work_order" ADD CONSTRAINT "oh_work_order_order_code_key" UNIQUE ("order_code");

-- ----------------------------
-- Primary Key structure for table oh_work_order
-- ----------------------------
ALTER TABLE "oh_boot"."oh_work_order" ADD CONSTRAINT "oh_work_order_pkey" PRIMARY KEY ("id");
