/*
 Navicat Premium Dump SQL

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80042 (8.0.42-0ubuntu0.24.04.2)
 Source Host           : localhost:3306
 Source Schema         : oh-sys3.0

 Target Server Type    : MySQL
 Target Server Version : 80042 (8.0.42-0ubuntu0.24.04.2)
 File Encoding         : 65001

 Date: 26/07/2025 22:47:56
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for sys_menu
-- ----------------------------
DROP TABLE IF EXISTS `sys_menu`;
CREATE TABLE `sys_menu` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `parent_id` bigint DEFAULT NULL COMMENT '上级ID，一级菜单为0',
  `name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '菜单名称',
  `title` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '标题',
  `path` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '显示路径',
  `menu_path` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '页面组件路径',
  `status` int DEFAULT '1' COMMENT '状态 0停用 1有效',
  `hide_in_menu` tinyint(1) DEFAULT '0' COMMENT '菜单是否隐藏',
  `hide_in_tab` tinyint(1) DEFAULT '0' COMMENT '标签是否隐藏',
  `authority` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '授权标识(多个用逗号分隔，如：sys:menu:list,sys:menu:save)',
  `badge` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '用于配置页面的徽标，会在菜单显示',
  `badge_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '用于配置页面的徽标类型，dot 为小红点，normal 为文本',
  `badge_variants` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '用于配置页面的徽标颜色',
  `affix_tab` tinyint(1) DEFAULT '0' COMMENT '用于配置页面是否固定标签页，固定后页面不可关闭',
  `link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '用于配置外链跳转路径',
  `type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'menu' COMMENT '类型:  catalog | menu | action',
  `open_style` tinyint DEFAULT '0' COMMENT '打开方式   0：内部   1：外部',
  `icon` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '菜单图标',
  `keep_alive` tinyint(1) DEFAULT '0' COMMENT '菜单缓存',
  `sort` int DEFAULT NULL COMMENT '排序',
  `db_status` tinyint DEFAULT '1' COMMENT '数据状态标识 0：已删除，1：正常',
  `mark` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `creator` bigint DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updater` bigint DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_pid` (`parent_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='菜单管理';

-- ----------------------------
-- Records of sys_menu
-- ----------------------------
BEGIN;
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (1, 0, 'Dashboard', '概览', '/dashboard', NULL, 1, 0, 0, '', NULL, NULL, NULL, 0, NULL, 'menu', 0, 'lucide:layout-dashboard', 1, 0, 1, NULL, 10000, '2023-09-24 20:13:47', 10000, '2025-05-26 13:39:51');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (2, 1, 'WorkSpace', '工作台', '/workspace', '/dashboard/workspace/index', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:workspace', 1, 0, 1, NULL, 10000, '2023-09-24 20:13:47', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (3, 1, 'Analytics', '分析页', '/analytics', '/dashboard/analytics/index', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'lucide:area-chart', 1, 1, 1, NULL, 10000, '2023-09-24 20:13:47', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (5, 10, 'SystemSetting', '系统设置', '/system/setting', NULL, 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:settings-check', 0, 0, 1, NULL, 10000, '2025-06-22 14:05:38', 10000, '2025-06-22 14:18:50');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (6, 10, 'SystemAuthority', '权限管理', '/system/authority', NULL, 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:delivery-settings', 0, 0, 1, NULL, 10000, '2025-06-22 14:07:19', 10000, '2025-06-22 14:19:02');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (7, 10, 'SystemApp', '系统应用', '/system/app', NULL, 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:app', 0, 0, 1, NULL, 10000, '2025-06-22 14:09:17', 10000, '2025-06-22 14:19:12');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (10, 0, 'System', '系统管理', '/sys', NULL, 1, 0, 0, '', NULL, 'dot', NULL, 0, NULL, 'menu', 0, 'carbon:settings', 1, 0, 1, NULL, 10000, '2023-09-24 20:13:47', 10000, '2025-05-07 10:16:33');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (11, 5, 'Menu', '菜单管理', '/system/menu', '/system/menu/list', 1, 0, 0, NULL, 'new', 'normal', 'default', 0, NULL, 'menu', 0, 'carbon:menu', 1, 0, 1, NULL, 10000, '2023-06-04 21:03:59', 10000, '2025-06-22 14:20:37');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (12, 11, '查询菜单', '查询菜单', '', NULL, 1, 0, 0, 'sys:menu:list,sys:menu:info,sys:role:menu', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 1, 0, 1, NULL, 10000, '2023-09-24 20:13:47', 10000, '2025-06-06 10:12:33');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (13, 11, '新增修改菜单', '新增修改菜单', '', NULL, 1, 0, 0, 'sys:menu:save,sys:menu:update,sys:menu:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 1, 0, 1, NULL, 10000, '2023-09-24 20:13:47', 10000, '2025-06-06 10:11:39');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (15, 6, 'Role', '角色管理', '/system/role', '/system/role/list', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'mdi:account-group', 1, 0, 1, NULL, 10000, '2023-06-04 21:03:59', 10000, '2025-06-22 14:19:26');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (16, 15, '查询角色', '查询角色', NULL, NULL, 1, 0, 0, 'sys:role:page,sys:role:list,sys:role:info', NULL, '', NULL, 0, NULL, 'action', 0, NULL, 1, 1, 1, NULL, 10000, '2023-09-24 20:13:47', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (17, 15, '新增修改角色', '新增修改角色', NULL, NULL, 1, 0, 0, 'sys:role:save,sys:role:update,sys:role:delete', NULL, '', NULL, 0, NULL, 'action', 0, NULL, 1, 1, 1, NULL, 10000, '2023-09-24 20:13:47', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (19, 6, 'Dept', '部门管理', '/system/dept', '/system/dept/list', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:container-services', 1, 0, 1, NULL, 10000, '2023-06-04 21:03:59', 10000, '2025-06-22 14:19:49');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (20, 19, '查询部门', '查询部门', NULL, NULL, 1, 0, 0, 'sys:dept:list,sys:dept:info', NULL, '', NULL, 0, NULL, 'action', 0, NULL, 1, 1, 1, NULL, 10000, '2023-09-24 20:13:47', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (21, 19, '新增修改部门', '新增修改部门', '', NULL, 1, 0, 0, 'sys:dept:save,sys:dept:update,sys:dept:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-08 14:22:58', 10000, '2025-05-08 14:23:29');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (23, 5, 'Params', '参数管理', '/system/params', '/system/params/index', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:delivery-parcel', 1, 0, 1, NULL, 10000, '2023-06-04 21:03:59', 10000, '2025-06-22 14:20:47');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (24, 23, '查询参数', '查询参数', '', NULL, 1, 0, 0, 'sys:params:all', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-08 14:22:58', 10000, '2025-05-08 14:23:29');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (25, 23, '新增修改参数', '新增修改参数', '', NULL, 1, 0, 0, 'sys:params:all', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-08 14:22:58', 10000, '2025-05-08 14:23:29');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (27, 6, 'Users', '用户管理', '/system/user', '/system/user/list', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:user-multiple', 1, 0, 1, NULL, 10000, '2023-06-04 21:03:59', 10000, '2025-06-22 14:19:59');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (28, 27, '查询用户', '查询用户', '', NULL, 1, 0, 0, 'sys:user:page,sys:user:info,sys:user:export', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-08 14:22:58', 10000, '2025-05-08 14:23:29');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (29, 27, '新增修改用户', '新增修改用户', '', NULL, 1, 0, 0, 'sys:user:save,sys:user:update,sys:user:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-08 14:22:58', 10000, '2025-05-08 14:23:29');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (30, 5, 'Dict', '字典管理', '/system/dict', '/system/dict/list', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:align-horizontal-left', 0, 0, 1, NULL, 10000, '2025-05-19 09:30:58', 10000, '2025-06-22 14:20:57');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (31, 30, '查询字典', '查询字典', '', NULL, 1, 0, 0, 'sys:dict:page,sys:dict:info,sys:dict:refreshTransCache', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-19 09:32:48', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (32, 30, '新增修改字典', '新增修改字典', '', NULL, 1, 0, 0, 'sys:dict:save,sys:dict:update,sys:dict:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-19 09:33:38', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (33, 6, 'Tenant', '租户管理', '/system/tenant', '/system/tenant/list', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:catalog-publish', 0, 0, 1, NULL, 10000, '2025-05-20 11:07:19', 10000, '2025-06-22 14:20:12');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (34, 33, '查询租户', '查询租户', '', NULL, 1, 0, 0, 'tenant:member:page,tenant:member:info', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-20 11:08:47', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (35, 33, '新增修改租户', '新增修改租户', '', NULL, 1, 0, 0, 'tenant:member:save,tenant:member:update', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-20 11:09:21', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (36, 6, 'Post', '岗位管理', '/system/post', '/system/post/list', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:calls-all', 1, 0, 1, NULL, 10000, '2025-05-20 17:54:23', 10000, '2025-06-22 14:20:26');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (37, 36, '查询岗位', '查询岗位', '', NULL, 1, 0, 0, 'sys:post:page,sys:post:info', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-20 17:55:22', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (38, 36, '新增修改岗位', '新增修改岗位', '', NULL, 1, 0, 0, 'sys:post:save,sys:post:update,sys:post:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-05-20 17:56:26', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (39, 7, 'Attachment', '附件管理', '/system/attachment', '/system/attachment/list', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:file-storage', 0, 0, 1, NULL, 10000, '2025-06-08 11:26:11', 10000, '2025-06-22 14:21:39');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (40, 39, '查询附件', '查询附件', '', NULL, 1, 0, 0, 'sys:attachment:page', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-08 11:27:23', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (41, 39, '新增修改附件', '新增修改附件', '', NULL, 1, 0, 0, 'sys:attachment:save,sys:attachment:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-08 11:28:09', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (42, 10, 'Log', '日志管理', '/system/log', NULL, 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:catalog', 0, 0, 1, NULL, 10000, '2025-06-11 17:24:35', 10000, '2025-06-11 17:29:17');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (43, 42, 'LoginLog', '登录日志', '/system/loginLog', '/system/log/loginLog', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:change-catalog', 0, 0, 1, NULL, 10000, '2025-06-11 17:25:59', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (44, 43, '查询登录日志', '查询登录日志', '', NULL, 1, 0, 0, 'sys:log:login', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-11 20:35:32', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (45, 42, 'OpLog', '操作日志', '/system/opLog', '/system/log/opLog', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:border-top', 0, 0, 1, NULL, 10000, '2025-06-11 17:28:36', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (46, 45, '查询操作日志', '查询操作日志', '', NULL, 1, 0, 0, 'sys:operate:all', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-11 20:40:14', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (47, 7, 'SystemInterface', '接口管理', '/system/app/manage', '', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:ibm-cloud-vpc-client-vpn', 0, 0, 1, NULL, 10000, '2025-06-22 20:39:43', 10000, '2025-06-22 20:43:16');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (48, 47, 'SystemAppInterface', '客户端管理', '/system/app/list', '/system/app/list', 1, 0, 0, '', NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:multiuser-device', 0, 0, 1, NULL, 10000, '2025-06-22 20:42:06', 10000, '2025-06-22 20:46:05');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (49, 48, '查询客户端', '查询客户端', '', NULL, 1, 0, 0, 'sys:app:page,sys:app:info,sys:function:page', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-22 20:46:30', 10000, '2025-06-23 15:13:02');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (50, 48, '新增修改客户端', '新增修改客户端', '', NULL, 1, 0, 0, 'sys:app:save,sys:app:update,sys:app:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-24 14:27:08', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (51, 47, 'SystemFunc', '接口管理', '/system/app/func', '/system/app/funcList', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:interface-usage-1', 0, 0, 1, NULL, 10000, '2025-06-25 10:35:16', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (52, 51, '查询接口', '查询接口', '', NULL, 1, 0, 0, 'sys:function:page,sys:function:info', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-25 10:36:10', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (53, 51, '新增修改接口', '新增修改接口', '', NULL, 1, 0, 0, 'sys:function:save,sys:function:update,sys:function:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-25 11:00:12', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (54, 47, 'SystemAppLog', '接口日志', '/system/app/log', '/system/app/log', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:catalog-publish', 0, 0, 1, NULL, 10000, '2025-06-25 17:27:26', 10000, '2025-06-25 17:30:01');
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (55, 54, '查询日志', '查询日志', '', NULL, 1, 0, 0, 'sys:app:page', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-25 17:28:11', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (56, 54, '删除日志', '删除日志', '', NULL, 1, 0, 0, 'sys:app:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-25 17:28:37', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (57, 43, '删除登录日志', '删除登录日志', '', NULL, 1, 0, 0, 'sys:log:login:delete', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-06-25 19:45:26', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (58, 7, 'UserMonitor', '用户监控', '/system/userMonitor', '/system/user/monitor', 1, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, 'menu', 0, 'carbon:cloud-monitoring', 0, 0, 1, NULL, 10000, '2025-07-13 19:25:32', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (59, 58, '在线用户', '在线用户', '', NULL, 1, 0, 0, 'monitor:user:all', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-07-13 19:34:04', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (60, 58, '强制退出', '强制退出', '', NULL, 1, 0, 0, 'monitor:user:logout', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-07-13 19:34:36', NULL, NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `title`, `path`, `menu_path`, `status`, `hide_in_menu`, `hide_in_tab`, `authority`, `badge`, `badge_type`, `badge_variants`, `affix_tab`, `link`, `type`, `open_style`, `icon`, `keep_alive`, `sort`, `db_status`, `mark`, `creator`, `create_time`, `updater`, `update_time`) VALUES (61, 58, '用户token列表', '用户token列表', '', NULL, 1, 0, 0, 'monitor:user:tokens', NULL, NULL, NULL, 0, NULL, 'action', 0, NULL, 0, 0, 1, NULL, 10000, '2025-07-26 22:47:10', NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
