services:
  oh-server:
    image: oh-boot:1.0.0
    container_name: oh-server
    restart: unless-stopped
    ports:
      - "5710:5710"
    environment:
      - spring.profiles.active=prod
      - JAVA_OPTS=-Xms2048M -Xmx2048M  # 还可以动态调整内存
      - LICENSE_MACHINE_CODE=my-server-2026
    volumes:
      - /home/finn/data/oh-server.jar:/app/oh-server.jar

  finn-redis:
    image: redis:7-alpine
    container_name: finn-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /home/finn/data/redis:/data        # 改为普通目录
    command: redis-server --appendonly yes --requirepass Finn!2026r

  finn-postgres:
    image: postgres:18-alpine
    container_name: finn-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Finn!2026p
      POSTGRES_DB: stepping_stone
    volumes:
      - /home/finn/data/postgres:/var/lib/postgresql/data   # 改为普通目录，指向 data 子目录

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    ports:
      - "9333:9333"   # Master UI
      - "8080:8080"   # Volume
      - "8888:8888"   # Filer UI
      - "8333:8333"   # S3 API
    volumes:
      - /home/finn/data/seaweedfs:/data
      - ./s3-config.json:/etc/seaweedfs/s3.json:ro
    command: >
      server -s3 -s3.config=/etc/seaweedfs/s3.json
      -dir=/data -volume.max=0 -master.volumeSizeLimitMB=1024
    restart: unless-stopped