services:
  oh-server:
    image: oh-boot:1.0.0
    container_name: oh-server
    restart: unless-stopped
    ports:
      - "5710:5710"
    environment:
      - spring.profiles.active=prod
      - JAVA_OPTS=-Xms2048M -Xmx2048M  # 还可以动态调整内存
      - LICENSE_MACHINE_CODE=my-server-2026
    volumes:
      - /home/finn/data/oh-server.jar:/app/oh-server.jar

  finn-redis:
    image: redis:7-alpine
    container_name: finn-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass Finn!2026r

  finn-postgres:
    image: postgres:18-alpine
    container_name: finn-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Finn!2026p
      POSTGRES_DB: stepping_stone
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  redis_data:
  postgres_data:
